[2022-03-16 22:26:47,197: INFO: stage_02_preprocessing]: 
********************
[2022-03-16 22:26:47,197: INFO: stage_02_preprocessing]: >>>>> stage Stage 02 Preprocessing Data started <<<<<
[2022-03-16 22:26:47,197: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-16 22:26:47,197: INFO: common]: created directory at: data\processed_data
[2022-03-16 22:26:47,213: INFO: stage_02_preprocessing]: Step-1 ==> Language Detection started
[2022-03-16 22:27:14,120: INFO: stage_02_preprocessing]: Step-1 ==> Language Detection Ended
[2022-03-16 22:27:14,120: INFO: stage_02_preprocessing]: Step-2 ==> Gibberish Detection Started
[2022-03-16 22:27:14,620: INFO: stage_02_preprocessing]: Step-2 ==> Gibberish Detection Ended
[2022-03-16 22:27:14,620: INFO: stage_02_preprocessing]: Step-3 ==> Profanity Detection Started
[2022-03-16 22:27:15,277: INFO: stage_02_preprocessing]: Step-3 ==> Profanity Detection Ended
[2022-03-16 22:27:15,277: INFO: stage_02_preprocessing]: Step-4 ==> Company Tag Removal Started
[2022-03-16 22:27:21,679: INFO: stage_02_preprocessing]: Step-4 ==> Company Tag Removal Ended
[2022-03-16 22:27:21,726: INFO: stage_02_preprocessing]: Completed all the Stages in preprocessing data was stored in data\processed_data\processed.csv
[2022-03-16 22:27:21,726: INFO: stage_02_preprocessing]: >>>>> stage Stage 02 Preprocessing Data completed!<<<<<

[2022-03-16 22:27:26,010: INFO: stage_01_get_data]: 
********************
[2022-03-16 22:27:26,010: INFO: stage_01_get_data]: >>>>> stage Stage 01 Extracting Data started <<<<<
[2022-03-16 22:27:26,010: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-16 22:27:26,010: INFO: common]: yaml file: configs/credentials.yaml loaded successfully
[2022-03-16 22:27:26,010: INFO: common]: created directory at: data
[2022-03-16 22:27:26,010: INFO: common]: created directory at: data\extracted_data
[2022-03-16 22:27:26,010: INFO: stage_01_get_data]: verifying the credentials
[2022-03-16 22:27:47,337: INFO: stage_01_get_data]: Started downloading the data
[2022-03-16 22:27:47,549: INFO: stage_01_get_data]: Successfully saved the data in data\extracted_data\products.csv
[2022-03-16 22:27:48,016: INFO: stage_01_get_data]: >>>>> stage Stage 01 Extracting Data completed!<<<<<

[2022-03-17 11:12:50,483: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-17 11:13:37,460: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-17 11:15:10,245: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-17 20:08:55,752: INFO: stage_02_preprocessing]: 
********************
[2022-03-17 20:08:55,774: INFO: stage_02_preprocessing]: >>>>> stage Stage 02 Preprocessing Data started <<<<<
[2022-03-17 20:08:55,778: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-17 20:08:55,778: INFO: common]: created directory at: data\processed_data
[2022-03-17 20:08:56,093: INFO: stage_02_preprocessing]: Step-1 ==> Language Detection started
[2022-03-17 20:09:22,078: INFO: stage_02_preprocessing]: Step-1 ==> Language Detection Ended
[2022-03-17 20:09:22,078: INFO: stage_02_preprocessing]: Step-2 ==> Gibberish Detection Started
[2022-03-17 20:09:22,884: INFO: stage_02_preprocessing]: Step-2 ==> Gibberish Detection Ended
[2022-03-17 20:09:22,884: INFO: stage_02_preprocessing]: Step-3 ==> Profanity Detection Started
[2022-03-17 20:09:23,539: INFO: stage_02_preprocessing]: Step-3 ==> Profanity Detection Ended
[2022-03-17 20:09:23,539: INFO: stage_02_preprocessing]: Step-4 ==> Company Tag Removal Started
[2022-03-17 20:09:24,603: INFO: stage_02_preprocessing]: Step-4 ==> Company Tag Removal Ended
[2022-03-17 20:09:24,964: INFO: stage_02_preprocessing]: Completed all the Stages in preprocessing data was stored in data\processed_data\processed.csv
[2022-03-17 20:09:24,964: INFO: stage_02_preprocessing]: >>>>> stage Stage 02 Preprocessing Data completed!<<<<<

[2022-03-17 20:09:57,655: INFO: stage_03_feature_engineering]: 
********************
[2022-03-17 20:09:57,655: INFO: stage_03_feature_engineering]: >>>>> stage Stage 03 Feature Engineering started <<<<<
[2022-03-17 20:09:57,660: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-17 20:09:57,661: INFO: common]: created directory at: data\feature_processed
[2022-03-17 20:09:57,669: INFO: stage_03_feature_engineering]: Added New Columns {Noun Strength,Review Polarity,Review Subjectivity,Review Complexity,Service Tagger,Compound Score}
[2022-03-17 20:11:39,594: INFO: stage_03_feature_engineering]: Successfully saved the file in data\feature_processed\feature.csv
[2022-03-17 20:11:39,594: INFO: stage_03_feature_engineering]: >>>>> stage Stage 03 Feature Engineering completed!<<<<<

[2022-03-17 20:11:47,258: INFO: stage_01_get_data]: 
********************
[2022-03-17 20:11:47,259: INFO: stage_01_get_data]: >>>>> stage Stage 01 Extracting Data started <<<<<
[2022-03-17 20:11:47,262: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-03-17 20:11:47,264: INFO: common]: yaml file: configs/credentials.yaml loaded successfully
[2022-03-17 20:11:47,264: INFO: common]: created directory at: data
[2022-03-17 20:11:47,264: INFO: common]: created directory at: data\extracted_data
[2022-03-17 20:11:47,265: INFO: stage_01_get_data]: verifying the credentials
[2022-03-17 20:12:59,717: ERROR: stage_01_get_data]: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
Traceback (most recent call last):
  File "src/stage_01_get_data.py", line 43, in main
    csv_obj = client.get_object(Bucket=bucketname, Key=filename)
  File "C:\Users\Dheeraj kumar\anaconda3\envs\sentiment-analysis\lib\site-packages\botocore\client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\Dheeraj kumar\anaconda3\envs\sentiment-analysis\lib\site-packages\botocore\client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
[2022-03-17 20:12:59,781: ERROR: stage_01_get_data]: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
Traceback (most recent call last):
  File "src/stage_01_get_data.py", line 62, in <module>
    main(config_path=parsed_args.config,creditionals_path=parsed_args.credentials)
  File "src/stage_01_get_data.py", line 52, in main
    raise e
  File "src/stage_01_get_data.py", line 43, in main
    csv_obj = client.get_object(Bucket=bucketname, Key=filename)
  File "C:\Users\Dheeraj kumar\anaconda3\envs\sentiment-analysis\lib\site-packages\botocore\client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\Dheeraj kumar\anaconda3\envs\sentiment-analysis\lib\site-packages\botocore\client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
